# Generated by Django 5.1.1 on 2024-10-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
