# Generated by Django 5.1.1 on 2024-10-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
