# Generated by Django 5.1.1 on 2024-10-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
