# Generated by Django 5.1.1 on 2024-10-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
